# Workflow Script: Simple population of spiking neurons
# Generated: 2025-09-18 21:00:00
# Original execution: 2025-09-18 20:59:59
# Execution order: ['pyramidal neuron', 'cortical_population']
# Total nodes: 2

# This script was automatically generated from NeuroWorkflow execution
# Each section corresponds to a node that was executed in the workflow

# === IMPORTS ===
import nest
import numpy as np

# === pyramidal neuron (single_neuron_builder) ===
# Execution order: 0
# Single Neuron: Pyramidal Neuron L2/3 (PyL23)
# Generated by NeuroWorkflow SingleNeuronBuilderNode
# Model Type: point_process
# Cell Class: excitatory


# === BIOLOGICAL PROPERTIES ===
# Dendrite extent: 300.0 μm
# Dendrite diameter: 2.5 μm
# Neurotransmitters: ['AMPA', 'NMDA']
# PSP amplitudes: {'AMPA': 0.8, 'NMDA': 0.4}
# Rise times: {'AMPA': 2.0, 'NMDA': 15.0}
# Firing rates - Resting: [2.0, 8.0] Hz
# Firing rates - Active: [15.0, 40.0] Hz
# Firing rates - Maximum: [60.0, 120.0] Hz

# === NEST MODEL CREATION ===
nest.CopyModel("iaf_psc_alpha", "iaf_psc_alpha_custom")
nest.SetDefaults("iaf_psc_alpha_custom", {
                        "V_th": -50.0,
                        "C_m": 200.0,
                        "tau_m": 15.0,
                        "V_reset": -70.0,
                        "t_ref": 2.0
                    })
pyl23 = nest.Create("iaf_psc_alpha_custom", 1)

print(f"Created neuron: {pyl23}")
print(f"Model template: iaf_psc_alpha_custom")

# === cortical_population (population_builder) ===
# Execution order: 1
# Population: Layer 2/3 Pyramidal Neurons (L23Pyr)
# Generated by NeuroWorkflow PopulationBuilderNode
# Brain Region: Primary Visual Cortex
# Population Size: 500 neurons (single hemisphere)
# Model Type: point_process
# Spatial: 3D


# === POPULATION BIOLOGICAL CONTEXT ===
# Density: 25000 neurons/mm³
# Tissue volume: 0.2 mm³
# Reference: Schüz & Palm (1989)
# Species: human
# Estimation method: stereological counting
# Spatial bounds: {'x': (0.0, 500.0), 'y': (0.0, 500.0), 'z': (0.0, 300.0)}

# === SPATIAL POSITIONS ===
# 3D positions for 500 neurons
# Spatial bounds: {'x': (0.0, 500.0), 'y': (0.0, 500.0), 'z': (0.0, 300.0)}

# Generate spatial positions
positions = np.zeros((500, 3))
positions[:, 0] = np.random.uniform(0.0, 500.0, 500)  # x coordinates
positions[:, 1] = np.random.uniform(0.0, 500.0, 500)  # y coordinates
positions[:, 2] = np.random.uniform(0.0, 300.0, 500)  # z coordinates

# === POPULATION CREATION ===
# Using neuron model from SingleNeuronBuilderNode: iaf_psc_alpha_custom
# Create population with 3D spatial positions
nest_positions = nest.spatial.free(positions.tolist())
l23pyr = nest.Create("iaf_psc_alpha_custom", 500, positions=nest_positions)

# Print status of one neuron from the population
neuron_status = nest.GetStatus(l23pyr[0])
print(f"Status of first neuron: {neuron_status}")

# === POPULATION SUMMARY ===
print(f"Created population: {len(l23pyr)} Layer 2/3 Pyramidal Neurons")
print(f"Population IDs: {l23pyr}")
print(f"Model: iaf_psc_alpha_custom")
print(f"Spatial organization: 3D positions")
