# Generated by Django 5.2 on 2025-09-04 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="pythonfile",
            table="box_pythonfile",
        ),
    ]
