# Workflow Script: Simple population of spiking neurons
# Generated: 2025-09-25 16:00:21
# Original execution: 2025-09-25 16:00:20
# Execution order: ['Parvalbumin-expressing interneuron', 'inhibitory cortical population', 'pyramidal neuron', 'cortical_population', 'connection from Inh to Exc Neurons', 'connection from Exc. to Inh Neurons.']
# Total nodes: 6

# This script was automatically generated from NeuroWorkflow execution
# Each section corresponds to a node that was executed in the workflow

# === IMPORTS ===
import nest
import numpy as np

# === Parvalbumin-expressing interneuron (single_neuron_builder) ===
# Execution order: 0
# Single Neuron: PV interneuron (PV)
# Generated by NeuroWorkflow SingleNeuronBuilderNode
# Model Type: point_process
# Cell Class: inhibitory


# === BIOLOGICAL PROPERTIES ===
# Dendrite extent: 200.0 μm
# Dendrite diameter: 2.0 μm
# Neurotransmitters: ['AMPA', 'NMDA']
# PSP amplitudes: {'AMPA': 0.5, 'NMDA': 0.3}
# Rise times: {'AMPA': 2.0, 'NMDA': 10.0}
# Firing rates - Resting: [1.0, 5.0] Hz
# Firing rates - Active: [10.0, 30.0] Hz
# Firing rates - Maximum: [50.0, 100.0] Hz

# === NEST MODEL CREATION ===
nest.CopyModel("iaf_psc_alpha", "iaf_psc_alpha_PV_custom")

# Inhibitory cell class defaults applied:
# V_th: -52.0
# V_reset: -65.0
# tau_m: 10.0
# t_ref: 1.0
nest.SetDefaults("iaf_psc_alpha_PV_custom", {
                        "C_m": 200.0,
                        "V_th": -52.0,
                        "V_reset": -65.0,
                        "tau_m": 10.0,
                        "t_ref": 1.0
                    })
pv = nest.Create("iaf_psc_alpha_PV_custom", 1)

print(f"Created neuron: {pv}")
print(f"Model template: iaf_psc_alpha_PV_custom")

# === inhibitory cortical population (population_builder) ===
# Execution order: 1
# Population: Layer of PV neurons (PVpop)
# Generated by NeuroWorkflow PopulationBuilderNode
# Brain Region: Primary Visual Cortex
# Population Size: 100 neurons (single hemisphere)
# Model Type: point_process
# Spatial: 3D


# === POPULATION BIOLOGICAL CONTEXT ===
# Spatial bounds: {'x': (0.0, 2.0), 'y': (0.0, 2.0), 'z': (0.0, 1.0)}

# === SPATIAL POSITIONS ===
# 3D positions for 100 neurons
# Spatial bounds: {'x': (0.0, 2.0), 'y': (0.0, 2.0), 'z': (0.0, 1.0)}

# Generate spatial positions
positions = np.zeros((100, 3))
positions[:, 0] = np.random.uniform(0.0, 2.0, 100)  # x coordinates
positions[:, 1] = np.random.uniform(0.0, 2.0, 100)  # y coordinates
positions[:, 2] = np.random.uniform(0.0, 1.0, 100)  # z coordinates

# === POPULATION CREATION ===
# Using neuron model from SingleNeuronBuilderNode: iaf_psc_alpha_PV_custom
# Create population with 3D spatial positions
nest_positions = nest.spatial.free(positions.tolist())
pvpop = nest.Create("iaf_psc_alpha_PV_custom", 100, positions=nest_positions)

# Print status of one neuron from the population
neuron_status = nest.GetStatus(pvpop[0])
print(f"Status of first neuron: {neuron_status}")

# === POPULATION SUMMARY ===
print(f"Created population: {len(pvpop)} Layer of PV neurons")
print(f"Population IDs: {pvpop}")
print(f"Model: iaf_psc_alpha_PV_custom")
print(f"Spatial organization: 3D positions")

# === pyramidal neuron (single_neuron_builder) ===
# Execution order: 2
# Single Neuron: Pyramidal Neuron L2/3 (PyL23)
# Generated by NeuroWorkflow SingleNeuronBuilderNode
# Model Type: point_process
# Cell Class: excitatory


# === BIOLOGICAL PROPERTIES ===
# Dendrite extent: 300.0 μm
# Dendrite diameter: 2.5 μm
# Neurotransmitters: ['AMPA', 'NMDA']
# PSP amplitudes: {'AMPA': 0.8, 'NMDA': 0.4}
# Rise times: {'AMPA': 2.0, 'NMDA': 15.0}
# Firing rates - Resting: [2.0, 8.0] Hz
# Firing rates - Active: [15.0, 40.0] Hz
# Firing rates - Maximum: [60.0, 120.0] Hz

# === NEST MODEL CREATION ===
nest.CopyModel("iaf_psc_alpha", "iaf_psc_alpha_PyL23_custom")
nest.SetDefaults("iaf_psc_alpha_PyL23_custom", {
                        "V_th": -50.0,
                        "C_m": 200.0,
                        "tau_m": 15.0,
                        "V_reset": -70.0,
                        "t_ref": 2.0
                    })
pyl23 = nest.Create("iaf_psc_alpha_PyL23_custom", 1)

print(f"Created neuron: {pyl23}")
print(f"Model template: iaf_psc_alpha_PyL23_custom")

# === cortical_population (population_builder) ===
# Execution order: 3
# Population: Layer 2/3 Pyramidal Neurons (L23Pyr)
# Generated by NeuroWorkflow PopulationBuilderNode
# Brain Region: Primary Visual Cortex
# Population Size: 800 neurons (single hemisphere)
# Model Type: point_process
# Spatial: 3D


# === POPULATION BIOLOGICAL CONTEXT ===
# Density: 25000 neurons/mm³
# Tissue volume: 0.2 mm³
# Reference: Schüz & Palm (1989)
# Species: human
# Estimation method: stereological counting
# Spatial bounds: {'x': (0.0, 2.0), 'y': (0.0, 2.0), 'z': (0.0, 1.0)}

# === SPATIAL POSITIONS ===
# 3D positions for 800 neurons
# Spatial bounds: {'x': (0.0, 2.0), 'y': (0.0, 2.0), 'z': (0.0, 1.0)}

# Generate spatial positions
positions = np.zeros((800, 3))
positions[:, 0] = np.random.uniform(0.0, 2.0, 800)  # x coordinates
positions[:, 1] = np.random.uniform(0.0, 2.0, 800)  # y coordinates
positions[:, 2] = np.random.uniform(0.0, 1.0, 800)  # z coordinates

# === POPULATION CREATION ===
# Using neuron model from SingleNeuronBuilderNode: iaf_psc_alpha_PyL23_custom
# Create population with 3D spatial positions
nest_positions = nest.spatial.free(positions.tolist())
l23pyr = nest.Create("iaf_psc_alpha_PyL23_custom", 800, positions=nest_positions)

# Print status of one neuron from the population
neuron_status = nest.GetStatus(l23pyr[0])
print(f"Status of first neuron: {neuron_status}")

# === POPULATION SUMMARY ===
print(f"Created population: {len(l23pyr)} Layer 2/3 Pyramidal Neurons")
print(f"Population IDs: {l23pyr}")
print(f"Model: iaf_psc_alpha_PyL23_custom")
print(f"Spatial organization: 3D positions")

# === connection from Inh to Exc Neurons (connection_builder) ===
# Execution order: 4
# Neural Connection: IE indegree
# Generated by NeuroWorkflow ConnectionBuilderNode
# Timestamp: 2025-09-25 16:00:09


# Connection: IE indegree
# Type: inhibitory
# Rule: fixed_indegree

# === SYNAPSE MODEL SETUP ===
base_synapse = 'static_synapse'
custom_synapse = 'static_synapse_custom_connection_from_Inh_to_Exc_Neurons'

# Copy base synapse model
nest.CopyModel(base_synapse, custom_synapse)

# === CONNECTION DICTIONARY ===
cdict = {'allow_autapses': False, 'rule': 'fixed_indegree', 'indegree': 1, 'allow_multapses': False, 'mask': {'spherical': {'radius': 1.0}}}

# === SYNAPSE DICTIONARY (User-defined weight) ===
# User provided weight in synapse_dict

sdict = {'synapse_model': 'static_synapse_custom_connection_from_Inh_to_Exc_Neurons', 'weight': 10.0, 'delay': 1.0}

# === CREATE CONNECTIONS ===
# Note: Make sure you have defined your population variables:
# pvpop = your_source_population
# l23pyr = your_target_population

# Create connections (single synapse dict - user-defined weight)
nest.Connect(pvpop, l23pyr, cdict, sdict)

# Get connection information
# connections = nest.GetConnections(pvpop, l23pyr)
# print(f'Created {{len(connections)}} connections')

# === BIOLOGICAL PROPERTIES ===
# Axon organization: focused (radius: 1.0 mm)
# Projection percentage: 100.0%
# Bouton number: 50
# Receptor location: none (None)
# Redundancy: 50.0
# Base weight: 10.0 (effective weight calculated at runtime)

# === connection from Exc. to Inh Neurons. (connection_builder) ===
# Execution order: 5
# Neural Connection: EI indegree
# Generated by NeuroWorkflow ConnectionBuilderNode
# Timestamp: 2025-09-25 16:00:09


# Connection: EI indegree
# Type: excitatory
# Rule: fixed_indegree

# === SYNAPSE MODEL SETUP ===
base_synapse = 'static_synapse'
custom_synapse = 'static_synapse_custom_connection_from_Exc._to_Inh_Neurons.'

# Copy base synapse model
nest.CopyModel(base_synapse, custom_synapse)

# === CONNECTION DICTIONARY ===
cdict = {'allow_autapses': False, 'rule': 'fixed_indegree', 'indegree': 4, 'allow_multapses': False, 'mask': {'spherical': {'radius': 0.5}}}

# === SYNAPSE DICTIONARY (User-defined weight) ===
# User provided weight in synapse_dict

sdict = {'synapse_model': 'static_synapse_custom_connection_from_Exc._to_Inh_Neurons.', 'weight': 4.0, 'delay': 1.0}

# === CREATE CONNECTIONS ===
# Note: Make sure you have defined your population variables:
# l23pyr = your_source_population
# pvpop = your_target_population

# Create connections (single synapse dict - user-defined weight)
nest.Connect(l23pyr, pvpop, cdict, sdict)

# Get connection information
# connections = nest.GetConnections(l23pyr, pvpop)
# print(f'Created {{len(connections)}} connections')

# === BIOLOGICAL PROPERTIES ===
# Axon organization: focused (radius: 0.5 mm)
# Projection percentage: 100.0%
# Bouton number: 50
# Receptor location: none (None)
# Redundancy: 100.0
# Base weight: 4.0 (effective weight calculated at runtime)
